### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by seabbs** [publichealthengland/coronavirus-dashboard-api-R-sdk#1]
Hi, 

Thanks for building out this interface - great work. 

When running the examples in the README I see the following: 

```
Error in get_request(filters, structure, page = current_page) : 
  Client errorNot FoundClient error: (404) Not Found
``` 

when running any `get_data` call. My colleague @kathsherratt has been able to replicate this issue and we have seen it across Mac, Linux, and Windows. 

We have been looking at supporting this data in our `covidregionaldata` aggregation package (https://cran.r-project.org/web/packages/covidregionaldata/index.html) but also haven't had any luck accessing the data when using the internal package code. 

Any ideas? 

It would be really great to have access to this data for our Rt estimation efforts (https://github.com/epiforecasts/covid-rt-estimates) and other research.

**Comment by seabbs** [comment]
So looking into this it may because some variables are missing and that causes the whole query to fail. 

Running the R code from the [API example](https://coronavirus.data.gov.uk/developers-guide#version) works as expected (note that package calls were missing from the example code meaning that it needed to be adapted in order to work/to have the `httr` package loaded). I assume the issue is death data being missing from the API. 

If this is correct the solutions that make sense to me are: 

1. Give an informative error message indicating which variable is causing the issue. 
2. Loop over variables required in the R code and then merge queries.
3. Update the API backend to be error-tolerant (if this is under your control).  


Example code adapted to work: 

```
endpoint <- 'https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=nation;areaName=england&structure={"date":"date","newCases":"newCasesByPublishDate"}'

httr::GET(
  url = endpoint,
  httr::timeout(10)
) -> response


if (response$status_code >= 400) {
  err_msg = httr::http_status(response)
  stop(err_msg)
}

# Convert response from binary to JSON:
json_text <- httr::content(response, "text")
data      <- jsonlite::fromJSON(json_text)

print(data)
```

**Comment by seabbs** [comment]
Dropping the deaths data from the call leads to successfully accessing the data so there is a good chance this is the issue. 

Code: 

```
library(ukcovid19)

query_filters <- c(
  'areaType=nation',
  'areaName=England'
)


cases_and_deaths = list(
  date = "date",
  areaName = "areaName",
  areaCode = "areaCode",
  newCasesByPublishDate = "newCasesByPublishDate",
  cumCasesByPublishDate = "cumCasesByPublishDate"
)


data <- get_data(
  filters = query_filters, 
  structure = cases_and_deaths
)

# Showing the head:
print(head(data))
```

@kathsherratt is looking at option 2. outlined above so we can access the available data asap if that is of interest.

**Comment by xenatisch** [comment]
That is indeed the issue... Death related metrics have been removed and there are currently no plans to restore them.  

Please see the [Developers Guide](https://coronavirus.data.gov.uk/developers-guide) for the latest metrics.

You should receive a meaningful message telling you that the metric is missing. A 404 request also signifies that the requested resource does not exist. 

We are working to make it easier for users to see available metrics within the SDK.

Apologies for the disruption.

**Comment by seabbs** [comment]
Is there any information as to why deaths related metrics have been removed with no plans to add back in? These are obviously very useful to have. Internally we used death data sourced from the DSTL but obviously having public data would be much better.

**Comment by xenatisch** [comment]
@seabbs I'm afraid it falls beyond our domain as the development team. 

It might be worth getting in touch via coronavirus-tracker@phe.gov.uk for any suggestions or request.

**Comment by seabbs** [comment]
Okay thanks. Having a clear resource listing data changes would be helpful from a developer perspective as if changes are expected as obviously any streaming application can't make use of this data without some certainty it will be present.

**Comment by xenatisch** [comment]
@seabbs To be fair, we have never removed metrics before - only added them - and have tried to maintain the service as robust as possible... It is serving of 30 million requests a day, so we implement any changes with extreme caution. 

We also update the Developers Guide on the website as soon as we add new metrics. There is a complete list over there.

Again, for what it's worth, I'm sorry for any disruptions.

**Comment by seabbs** [comment]
No problem. Perhaps I missed it but a changelog would be a great help. Thanks again for the work on all of this - its a great help.
